### ISSUE TITLE
TreeViewer closes when transforming .trees file 

### ISSUE THREAD

**Issue by lespacelay** [arklumpus/TreeViewer#40]
I am running Ubuntu 22. When I tried to open a .trees file, I was prompted to subset the file (and make a binary version). I ran the subsetting but when the process ended and got to the "Transforming trees" stage, the application closes with no error message. I thought it was the subsetting process, so I subset the tree file myself so that there were only 1000 trees in the nexus file. The application still dropped, again at the "Transforming trees" stage in the file processing.
Thanks for any help, and I understand the difficulties with having software run on multiple platforms, I appreciate that there is a linux version!

**Comment by arklumpus** [comment]
Hi! Thank you for using TreeViewer!

By any chance, do your taxon names include a `|` character? This could explain the crash.

Otherwise, would you be able to send me the file that causes the crash, please? Either here or via email. 

You can also try opening the command line and running `TreeViewer --log-exceptions > exceptions.txt`; this will create a file with more information about the error.

**Comment by lespacelay** [comment]
Thank you! 
Yes, my trees used the '|' character, I often use it in my alignment headers as my separator for providing metadata to BEAST. That'd be it. I will remove the '|' and maybe just phase out using it in further analyses if it conflicts with file formats or processes. Logging the exceptions is great, thank you - I am guessing it'd be easy to see that the '|' was the problem if I'd produced the log in the first place.

**Comment by foersterst** [comment]
Hi, 

I'm experiencing more or less the same problem here: TreeViewer closes without any error message every time I try to add a (string) tag to a clade. My tree file does not contain the "|" character. I'm running TreeViewer on Windows 11 x64.   

```
C:\Users\stenio>Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at PhyloTree.AttributeDictionary.TryGetValue(String name, Object& value)
   at TreeViewer.Extensions.GetAttributeType(TreeNode node, String attributeName)
   at TreeViewer.Extensions.GetAttributeType(TreeNode node, String attributeName)
   at Add_attribute.MyModule.OnParameterChange(Object tree, Dictionary`2 previousParameterValues, Dictionary`2 currentParameterValues, Dictionary`2& controlStatus, Dictionary`2& parametersToChange)
   at TreeViewer.MainWindow.<>c__DisplayClass228_0.<AddFurtherTransformation>b__11(Dictionary`2 previousParameterValues, Dictionary`2 currentParameterValues, Dictionary`2& controlStatus, Dictionary`2& parametersToChange)
   at TreeViewer.MainWindow.<>c__DisplayClass157_4.<UpdateParameterPanel>b__11(Dictionary`2 parametersToChange)
   at TreeViewer.MainWindow.AddAttributeButtonClicked(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at TreeViewer.Program.Main(String[] args)
```

Thank you! 

Very nice software.

**Comment by arklumpus** [comment]
Hi! It looks like you might have an empty name or another empty attribute... Could you send me the tree file, either here or via e-mail?

**Comment by foersterst** [comment]
> Hi! It looks like you might have an empty name or another empty attribute... Could you send me the tree file, either here or via e-mail?

Hi, indeed, that was the problem! Everything worked well when I added an `Attribute name` and the `Attribute value`.

Thank you!

**Comment by arklumpus** [comment]
Great, glad that solved it!
